flappybirdv0:
  env_id: FlappyBird-v0
  epsilon_init: 1
  epislon_min: 0.05
  epislon_decay: 0.9995
  replay_memory_size: 100000
  mini_batch_size: 32 
  network_sync_rate: 10 # for after every 10 step our target network get the snap shot of the policy network
  alpha: .001
  gamma : 0.99
  reward_threshold: 1000
  